[profile.default]
solc_version = '0.8.23'
src = "contracts"
out = "out"
libs = ["lib"]
test = 'test'
cache_path  = 'cache_forge'
evm_version = 'paris'
optimizer = true
optimizer_runs = 200
ignored_error_codes = []
remappings = [
    "@wormhole-solidity-sdk/=lib/wormhole-solidity-sdk/src/",
    "ds-test/=lib/wormhole-solidity-sdk/lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/wormhole-solidity-sdk/lib/forge-std/src/",
    "wormhole-solidity-sdk/=lib/wormhole-solidity-sdk/src/",
    "@zeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/=node_modules/@openzeppelin/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
