[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@wormhole-solidity-sdk/=lib/wormhole-solidity-sdk/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "ds-test/=lib/wormhole-solidity-sdk/lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/wormhole-solidity-sdk/lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "wormhole-solidity-sdk/=lib/wormhole-solidity-sdk/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
